Controllers/DetailProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NetProject.DbAccessor;
using NetProject.Models;

namespace NetProject.Controllers
{
    public class DetailProductController : Controller
    {
        private readonly ILogger<DetailProductController> _logger;
        private readonly CategoryData _categoryDataAcessor;
        private readonly TypeProductData _typeProductDataAcessor;
        private readonly ProductData _productDataAcessor;

        public DetailProductController(ILogger<DetailProductController> logger
           , CategoryData categoryDataAcessor
           , TypeProductData typeProductDataAcessor
           , ProductData productDataAcessor)
        {
            _logger = logger;
            _categoryDataAcessor = categoryDataAcessor;
            _typeProductDataAcessor = typeProductDataAcessor;
            _productDataAcessor = productDataAcessor;
        }


        [HttpGet]
        public IActionResult Index([FromQuery] int id_product)
        {
            ViewData["countPromotion"] = _productDataAcessor.CountPromotionProducts();
            ViewData["promotionProducts"] = _productDataAcessor.GetPromitionProduct();
            ViewData["relatedProduct"] = _productDataAcessor.GetProductByCategory(1);
            
           
            var cateProduct = _categoryDataAcessor.GetActiveCategoryProduct();
            ViewData["res_getCateProduct"] = cateProduct;
            foreach (var cate in cateProduct)
            {
                ViewData["res_getTypeProduct_" + cate.Id] = _typeProductDataAcessor.GetTypeProduct(cate.Id);
            }

            ViewData["res_statusDetailProduct"] = "visible";
            ViewData["res_statusDetailProduct"] = "visible";
            ViewData["id_cateChose"] = 0;
            ViewData["res_statusAdmin"] = "disible";

            ViewData["requestedProduct"] = _productDataAcessor.GetProductById(id_product);
            if (ViewData["requestedProduct"] == null) return NotFound();
            return View();
        }
    }
}

Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NetProject.DataAccessor;
using NetProject.DbAccessor;
using NetProject.EntryParams;
using NetProject.Models;
using NetProject.Session;

namespace NetProject.Controllers
{
    public class HomePageController : Controller
    {
        private readonly ILogger<HomePageController> _logger;
        private readonly SliderData _sliderDataAcessor;
        private readonly CategoryData _categoryDataAcessor;
        private readonly TypeProductData _typeProductDataAcessor;
        private readonly ProductData _productDataAcessor;
        private readonly AddressData _addressData;
        private readonly BillData _billData;
        private readonly BillDetailData _billDetailData;
        public HomePageController(ILogger<HomePageController> logger
            , SliderData sliderDataAcessor
            , CategoryData categoryDataAcessor
            , TypeProductData typeProductDataAcessor
            , ProductData productDataAcessor
            , AddressData addressData
            , BillData billData
            , BillDetailData billDetailData)
        {
            _logger = logger;
            _sliderDataAcessor = sliderDataAcessor;
            _categoryDataAcessor = categoryDataAcessor;
            _typeProductDataAcessor = typeProductDataAcessor;
            _productDataAcessor = productDataAcessor;
            _addressData = addressData;
            _billData = billData;
            _billDetailData = billDetailData;
        }

        public IActionResult Index()
        {
            ViewData["sliders"] = _sliderDataAcessor.GetSlidersIndex();
            ViewData["countPromotion"] = _productDataAcessor.CountPromotionProducts();
            ViewData["promotionProducts"] = _productDataAcessor.GetPromitionProduct();
            ViewData["hotSmartPhones"] = _productDataAcessor.GetProductByCategory(1);
            ViewData["hotAccessProducts"] = _productDataAcessor.GetProductByCategory(2);

            var cateProduct = _categoryDataAcessor.GetActiveCategoryProduct();
            ViewData["res_getCateProduct"] = cateProduct;
            foreach (var cate in cateProduct)
            {
                ViewData["res_getTypeProduct_" + cate.Id] = _typeProductDataAcessor.GetTypeProduct(cate.Id);
            }

            ViewData["res_statusHomePage"] = "visible";
            ViewData["id_cateChose"] = 0;
            ViewData["res_statusAdmin"] = "disible";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult ListCart()
        {
            ViewData["sliders"] = _sliderDataAcessor.GetSlidersIndex();
            ViewData["countPromotion"] = _productDataAcessor.CountPromotionProducts();
            ViewData["promotionProducts"] = _productDataAcessor.GetPromitionProduct();
            ViewData["hotSmartPhones"] = _productDataAcessor.GetProductByCategory(1);
            ViewData["hotAccessProducts"] = _productDataAcessor.GetProductByCategory(2);

            var cateProduct = _categoryDataAcessor.GetActiveCategoryProduct();
            ViewData["res_getCateProduct"] = cateProduct;
            foreach (var cate in cateProduct)
            {
                ViewData["res_getTypeProduct_" + cate.Id] = _typeProductDataAcessor.GetTypeProduct(cate.Id);
            }

            ViewData["res_statusHomePage"] = "visible";
            ViewData["id_cateChose"] = 0;
            ViewData["res_statusAdmin"] = "disible";
            return View();
        }
        [HttpGet]
        public IActionResult TypeProduct([FromQuery] int type_product)
        {
            ViewData["sliders"] = _sliderDataAcessor.GetSlidersIndex();
            ViewData["countPromotion"] = _productDataAcessor.CountPromotionProducts();
            ViewData["promotionProducts"] = _productDataAcessor.GetPromitionProduct();
            ViewData["hotSmartPhones"] = _productDataAcessor.GetProductByCategory(1);
            ViewData["hotAccessProducts"] = _productDataAcessor.GetProductByCategory(2);

            var cateProduct = _categoryDataAcessor.GetActiveCategoryProduct();
            ViewData["res_getCateProduct"] = cateProduct;
            foreach (var cate in cateProduct)
            {
                ViewData["res_getTypeProduct_" + cate.Id] = _typeProductDataAcessor.GetTypeProduct(cate.Id);
            }
            if (_typeProductDataAcessor.GetTypeProductById(type_product) == null) return NotFound();

            ViewData["res_statusHomePage"] = "disible";
            ViewData["id_cateChose"] = _typeProductDataAcessor.GetTypeProductById(type_product).IdCategory;
            ViewData["res_statusAdmin"] = "disible";



            var requestedTP = _typeProductDataAcessor.GetTypeProductById(type_product);
            ViewData["res_getNameTypeProductSmartPhone"] = _typeProductDataAcessor.GetNameTypeProductSmartPhone(requestedTP.IdCategory);
            ViewData["res_getAllTypeProductPromotion"] = _productDataAcessor.GetAllTypeProductPromotion(type_product);
            ViewData["res_getAllTypeProduct"] = _productDataAcessor.GetAllTypeProduct(type_product, 8, 0);
            ViewData["res_requestType"] = requestedTP;
            ViewData["activeType"] = type_product;

            if (_typeProductDataAcessor.GetTypeProductById(type_product).IdCategory == 1)
            {

                ViewData["res_getAllTypeProductSmartPhone"] = _typeProductDataAcessor.GetNameTypeProductSmartPhone(1);
                return View("CateSmartPhoneProduct");
            }
            else
                return NotFound();
        }

        [HttpGet]
        public IActionResult CheckOut()
        {
            var user = "";
            var cart = SessionFunction.GetCart(HttpContext.Session);
            if (user != null && cart.List.Count() > 0)
            {

                ViewData["sliders"] = _sliderDataAcessor.GetSlidersIndex();
                ViewData["countPromotion"] = _productDataAcessor.CountPromotionProducts();
                ViewData["promotionProducts"] = _productDataAcessor.GetPromitionProduct();
                ViewData["hotSmartPhones"] = _productDataAcessor.GetProductByCategory(1);
                ViewData["hotAccessProducts"] = _productDataAcessor.GetProductByCategory(2);

                var cateProduct = _categoryDataAcessor.GetActiveCategoryProduct();
                ViewData["res_getCateProduct"] = cateProduct;
                foreach (var cate in cateProduct)
                {
                    ViewData["res_getTypeProduct_" + cate.Id] = _typeProductDataAcessor.GetTypeProduct(cate.Id);
                }

                ViewData["res_statusHomePage"] = "disible";
                ViewData["id_cateChose"] = 0;
                ViewData["res_statusAdmin"] = "disible";
                ViewData["cities"] = _addressData.Cities();
                return View();
            }
            else
            {
                return Redirect("ListCart");
            }
        }
        [HttpPost]
        public IActionResult Order(CheckoutParams entries)
        {


            Cart cart = SessionFunction.GetCart(HttpContext.Session);
            User user = SessionFunction.GetUser(HttpContext.Session);

            if (user == null || cart == null || cart.List.Count() <= 0)
            {
                return Redirect("/");
            }
            else
            {

                var rs_city = _addressData.GetCity(entries.Select_City);
                var rs_district = _addressData.GetDistrict(entries.Select_District);

                var yourAdress = entries.YourAddress + ",\t" + rs_district.Name + ",\t" + rs_city.Name;
                if (entries.YourNote == null) entries.YourNote = "";


                string dateNow = System.DateTime.Now.ToString("yyyy-MM-dd");

                var bill = _billData.AddBill(new Bill {
                    Active = 1,
                    Address = yourAdress,
                    DateOrder = dateNow,
                    IdUser = user.Id,
                    Note = entries.YourNote,
                    TotalPrice = cart.Total
                
                });

                foreach (var item in cart.List)
                {
                    _billDetailData.AddBillDetail(new BillDetail
                    {
                        Active = 1 ,
                        IdBill = bill.Id,
                        IdProduct = item.Id,
                        Quantity = cart.Quantities[item.Id + ""],
                        TotalPrice = cart.Quantities[item.Id + ""] * (item.PricePromotion != 0 ? item.PricePromotion : item.PriceListed)
                    });
                }
                SessionFunction.SetCart(HttpContext.Session, new Cart());
            }
            return Redirect("/");
        }
        [HttpGet]
        public IActionResult PageNotFound()
        {
            return View("NotFound");
        }
    }
}

Views/HomePage/CateSmartPhoneProduct.cshtml
@{
    Layout = "_MasterLayout";
    ViewData["Title"] = "Home Page";
    List<Slider> sliders = (List<Slider>)ViewData["sliders"];
    int countPromotion = (int)ViewData["countPromotion"];
    List<Product> promotionProducts = (List<Product>)ViewData["promotionProducts"];
    List<Product> hotSmartPhones = (List<Product>)ViewData["hotSmartPhones"];
    List<Product> hotAccessProducts = (List<Product>)ViewData["hotAccessProducts"];

    List<TypeProduct> typeProducts = ViewData["res_getAllTypeProductSmartPhone"] as List<TypeProduct>;
    int activeType = (int)ViewData["activeType"];

    List<TypeProduct> smartphoneType = ViewData["res_getNameTypeProductSmartPhone"] as List<TypeProduct>;
    List<Product> allProductPromotion = ViewData["res_getAllTypeProductPromotion"] as List<Product>;
    var allTypeProduct = ViewData["res_getAllTypeProduct"] as Dictionary<string, object>;
    var requestTP = ViewData["res_requestType"] as TypeProduct;
}

<section id="section-5" class="mt-5">
    <div class="container">
        <div class="search_by_carrier col-md-12">
            @{
                foreach (var item in typeProducts)
                {
                    var routeData = new Dictionary<string, string>();
                    routeData.Add("type_product", item.Id + "");

                    if (item.Id == activeType)
                    {
                        <a asp-all-route-data="routeData" asp-action="TypeProduct" asp-controller="HomePage" style="background-color: #4caf503b"><img src="@item.ImageType" alt=""></a>
                    }
                    else
                    {
                        <a asp-all-route-data="routeData" asp-action="TypeProduct" asp-controller="HomePage"><img src="@item.ImageType" alt=""></a>
                    }
                }
            }
        </div>
        <div class="serch_by_price navbar col-md-8 mt-3">
            <ul class="nav">
                <li class="nav-item">
                    <h6 class="nav-link">Chọn mức giá</h6>
                </li>
                <li class="nav-item">
                    <a style="cursor: pointer" onclick="ajaxFindPrice(0,2000000,@activeType)" class="nav-link">Dưới 2 triệu</a>
                </li>
                <li class="nav-item">
                    <a style="cursor: pointer" onclick="ajaxFindPrice(2000000,4000000,@activeType)" class="nav-link">Từ 2 đến 4 triệu</a>
                </li>
                <li class="nav-item">
                    <a style="cursor: pointer" onclick="ajaxFindPrice(4000000,7000000,@activeType" class="nav-link">Từ 4 đến 7 triệu</a>
                </li>
                <li class="nav-item">
                    <a style="cursor: pointer" onclick="ajaxFindPrice(7000000,13000000,@activeType" class="nav-link">Từ 7 đến 13 triệu</a>
                </li>
                <li class="nav-item">
                    <a style="cursor: pointer" onclick="ajaxFindPrice(13000000,60000000,@activeType" class="nav-link">Trên 13 triệu</a>
                </li>
            </ul>
        </div>
    </div>
</section>

<!--section 4 -->
<section class="mt-5" id="section-4">
    <!-- container-->
    <div class="container">

        <!--modal image zoom-->
        <div class="modal fade" id="detail-product">
            <div class="modal-dialog modal-xl" id="txtDetail">

            </div>

        </div>

        <div id="txtFindPricePro">
            <!--menu title-->
           
            <span class="menu_title" style="text-transform: uppercase">Điện thoại @requestTP.NameType ĐANG KHUYẾN MÃI</span>
            <!--row-->
            <!--product-sale-->
            <div class="owl-carousel promotion-banner owl-theme mt-3 mb-4">

                @{
                    var index = 0;

                    foreach (var item in allProductPromotion)
                    {
                        var routeData = new Dictionary<string, string>();
                        routeData.Add("id_product", item.Id + "");
                        <div class="item">
                            <div class="card show-options">
                                <div class="ribbon-wrapper">
                                    <div class="ribbon sale">
                                        Sale
                                    </div>
                                </div>
                                <div class="card-body">
                                    <a asp-all-route-data="routeData" asp-action="Index" asp-controller="DetailProduct" class="card-link"><img class="card-img-top img-zoom" src="@item.ImageProduct" alt="Card image"></a>
                                </div><!--end card-body-->
                                <div class="card-footer">
                                    <h6>@item.NameProduct</h6>
                                    <div class="text-price">
                                        <p class="float-left txt_price"><strong>@NetProject.Util.MyFormat.ToVietNameseCurrency(item.PricePromotion)</strong></p>

                                        <p class="float-left txt_price_sale"><del>@NetProject.Util.MyFormat.ToVietNameseCurrency(item.PriceListed)</del></p>
                                    </div>
                                </div><!-- end card-footer-->
                                <div class="show-options-icon bg-light">
                                    <!-- add Cart-->
                                    <a style="cursor: pointer" onclick="ajaxAddProduct(@item.Id)" class="link-option"><i class="fas fa-cart-plus icon-green s--20px"></i></a>
                                    <!-- like-->
                                    <!-- detail-->
                                    <a onclick="ajaxGetInforProduct(@item.Id,0,1)" class="link-option" data-toggle="modal" data-target="#detail-product"><i class="fa fa-eye icon-green s--20px"></i></a>
                                </div>      <!--end show-text-->
                            </div><!--end card-->
                        </div>
                    }
                }
            </div>



            <!--menu title-->

            <span class="menu_title" style="text-transform: uppercase">ĐIỆN THOẠI @requestTP.NameType</span>
            <div id="txt_pagination">
                <!--row-->
                <div class="row ml-1 mt-3 mb-3">
                    <!--product-sale-->
                    @{
                        foreach (var item in (allTypeProduct["products"] as List<Product>))
                        {
                            var routeData = new Dictionary<string, string>();
                            routeData.Add("id_product", item.Id + "");
                            <li class="col-sm-3 mt-4 mb-4">
                                <div class="card show-options">
                                    @if (item.PricePromotion != 0)
                                    {
                                        <div class="ribbon-wrapper">
                                            <div class="ribbon sale">
                                                Sale
                                            </div>
                                        </div>
                                    }
                                    <div class="card-body">
                                        <a asp-all-route-data="routeData" asp-action="Index" asp-controller="DetailProduct" class="card-link"><img class="card-img-top img-zoom" src="@item.ImageProduct" alt="Card image"></a>
                                    </div><!--end card-body-->
                                    <div class="card-footer">
                                        <h6>@item.NameProduct</h6>
                                        <div class="text-price">
                                            <p class="float-left txt_price"><strong>@NetProject.Util.MyFormat.ToVietNameseCurrency(item.PricePromotion)</strong></p>
                                            <p class="float-left txt_price_sale"><del>@NetProject.Util.MyFormat.ToVietNameseCurrency(item.PriceListed)</del></p>

                                        </div>
                                    </div><!-- end card-footer-->
                                    <div class="show-options-icon bg-light">
                                        <!-- add Cart-->
                                        <a style="cursor: pointer" onclick="ajaxAddProduct(@item.Id)" class="link-option"><i class="fas fa-cart-plus icon-green s--20px"></i></a>
                                        <!-- like-->
                                        <!-- detail-->
                                        <a onclick="ajaxGetInforProduct(@item.Id,0,1)" class="link-option" data-toggle="modal" data-target="#detail-product"><i class="fa fa-eye icon-green s--20px"></i></a>
                                    </div>      <!--end show-text-->
                                </div><!--end card-->
                            </li>
                        }
                    }
                </div>

                <ul class="pagination">
                    @{
                        var totalProductCount = (int)allTypeProduct["total"];
                        double limit = 8;
                        int result_pag = (int)Math.Ceiling(totalProductCount / limit);
                        int int_limit = (int)8;
                    }

                    <li class="page-item"><a class="page-link" style="cursor: pointer" onclick="ajaxGetPagniation(@activeType, @int_limit, 0)">Trước</a></li>

                    @{
                        for (int i = 0; i < result_pag; i++)
                        {
                            if (i == 0)
                            {
                                <li class="page-item active"><a class="page-link" style="cursor: pointer" onclick="ajaxGetPagniation(@activeType,@int_limit, 0)">@(i+1)</a></li>
                            }
                            else
                            {
                                <li class="page-item"><a class="page-link" style="cursor: pointer" onclick="ajaxGetPagniation(@activeType, @int_limit, @(i*int_limit)">@(i+1)</a></li>
                            }
                        }
                    }
                    <li class="page-item"><a class="page-link" style="cursor: pointer" onclick="ajaxGetPagniation(@activeType, @int_limit, @int_limit)">Tiếp</a></li>
                </ul>
            </div>
        </div>
    </div>

</section>

<script>
    function ajaxFindPrice(priceFrom, priceTo, id_type) {
        var xhttp;
        xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("txtFindPricePro").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "http://localhost:8080/ProjectWeb/FindPriceProduct?priceFrom=" + priceFrom + "&priceTo=" + priceTo + "&id_type=" + id_type, true);
        xhttp.send();

    }

    function ajaxGetPagniation(id_type, limit, id_start) {
        var xhttp;
        xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("txt_pagination").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "http://localhost:8080/ProjectWeb/AjaxPaginationTypeProduct?type_product=" + id_type + "&limit=" + limit + "&id_start=" + id_start, true);
        xhttp.send();

    }
</script>

Views/HomePage/CheckOut.cshtml
@{
    Layout = "_MasterLayout";
    ViewData["Title"] = "Home Page";
    List<Slider> sliders = (List<Slider>)ViewData["sliders"];
    int countPromotion = (int)ViewData["countPromotion"];
    List<Product> promotionProducts = (List<Product>)ViewData["promotionProducts"];
    List<Product> hotSmartPhones = (List<Product>)ViewData["hotSmartPhones"];
    List<Product> hotAccessProducts = (List<Product>)ViewData["hotAccessProducts"];
    var cart = NetProject.Session.SessionFunction.GetCart(Context.Session);
    var user = NetProject.Session.SessionFunction.GetUser(Context.Session);
    List<City> cities = ViewData["cities"] as List<City>;
}
<div class="container" style="height: 588px">
    <h4 class="mb-5 mt-3">Đặt hàng</h4>

    <div class="row">
        <div class="col-sm-3">
            <h5>Tổng tiền:</h5>
            <h3 class="text-success">@NetProject.Util.MyFormat.ToVietNameseCurrency(cart.Total)</h3><br>
        </div>
        <div class="col-sm-8">
            <form asp-action="Order" asp-controller="HomePage" method="post">
                <div class="form-inline form-group">
                    <label class="col-sm-5" for="fullName">Họ tên:</label>
                    <input id="fullName" name="yourName" value="@user.NameUser" class="col-sm-7 form-control" required type="text">

                </div>
                <div class="form-inline form-group">
                    <label class="col-sm-5">Giới tính:</label>
                    <div class="row col-sm-7">
                        <div class="radio">
                            <label>
                                <input value="Nam" name="yourGender" type="radio" @(user.Gender.ToUpper().Equals("MALE") ? "checked" : "")>Nam
                            </label>
                        </div>
                        <div class="radio ml-5">
                            <label>
                                <input value="Nữ" name="yourGender" type="radio" @(user.Gender.ToUpper().Equals("FEMALE") ? "checked" : "")>Nữ
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-inline form-group">

                    <label class="col-sm-5">Thành phố/ Tỉnh</label>
                    <select id="select_city" name="select_city" class="form-control col-sm-7" onchange="cityChange(this.value)">
                        <option value="0">Chọn Thành phố/ Tỉnh</option>
                        @{
                            foreach (var item in cities)
                            {
                                <option value="@item.Id">@item.Name</option>
                            }
                        }
                    </select>
                </div>
                <div class="form-inline form-group">
                    <label class="col-sm-5">Quận/ Huyện:</label>
                    <select id="select_district" name="select_district" class="form-control col-sm-7">
                        <option value="0">Chọn Quận/ Huyện</option>
                    </select>
                </div>
                <div class="form-inline form-group">
                    <label class="col-sm-5" for="adrr">Số nhà, đường, phường/ xã:</label>
                    <input id="adrr" name="yourAddress" class="col-sm-7 form-control" type="text" required placeholder="vd: 52, đường Trần Hưng Đạo"></input>
                </div>
                <div class="form-inline form-group">
                    <label class="col-sm-5" for="numPhone">Điện thoại:</label>
                    <input id="numPhone" name="yourNumPhone" value="@user.NumberPhone" class="col-sm-7 form-control" required type="text"/>

                </div>
                <div class="form-inline form-group">
                    <label class="col-sm-5" for="note">Ghi chú: </label>
                    <textarea id="note" name="yourNote" class="col-sm-7 form-control" type="text"></textarea>

                </div>
                <div class="form-inline form-group">
                    <div class="col-sm-5"></div>
                    <button type="submit" onclick="validateFormCheckOut()" class="btn btn-primary col-sm-2">Đặt hàng</button>
                    <button type="reset" class="btn btn-warning col-sm-2">Làm trắng</button>
                    <button type="reset" class="btn btn-danger col-sm-2">Hủy</button>
                </div>

            </form>
        </div>
    </div>

</div>

<script>
    function cityChange(str) {
        var xhttp;
        if (str == "") {
            document.getElementById("select_district").innerHTML = "";
            return;
        }
        xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                document.getElementById("select_district").innerHTML = this.responseText;
            }
        };
        xhttp.open("GET", "/Ajax/GetDistrictOfCity?id_city=" + str, true);
        xhttp.send();
    }

    function validateFormCheckOut() {
        if (document.getElementById('select_city').value == 0) {
            alert("Vui lòng điền chọn đầy đủ để hàng được giao chính xác 1 ");
            document.getElementById('select_city').style.border = "1px solid red"
            event.preventDefault();
            return false;
        } else if (document.getElementById('select_district').value == 0) {
            alert("Vui lòng điền chọn đầy đủ để hàng được giao chính xác 2 ");
            document.getElementById('select_district').style.border = "1px solid red"
            event.preventDefault();
            return false;
        } else if (document.getElementById('adrr').value == '') {
            alert("Vui lòng điền chọn đầy đủ để hàng được giao chính xác 3 ");
            document.getElementById('adrr').style.border = "1px solid red"
            event.preventDefault();
            return false;
        } 
        return true;
    }
</script>

Views/HomePage/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<hear>
    <style>
        * {
            transition: all 0.6s;
        }

        html {
            height: 100%;
        }

        body {
            font-family: 'Lato', sans-serif;
            color: #888;
            margin: 0;
        }

        #main {
            display: table;
            width: 100%;
            height: 100vh;
            text-align: center;
        }

        .fof {
            display: table-cell;
            vertical-align: middle;
        }

            .fof h1 {
                font-size: 50px;
                display: inline-block;
                padding-right: 12px;
                animation: type .5s alternate infinite;
            }
    </style>
</hear>
<body>
    <div id="main">
        <div class="fof">
            <h1>Error 404</h1>
        </div>
    </div>
</body>
</html>